export const categories = [
    {
        id: '1',
        name: 'Electronics',
        slug: 'electronics',
        image: 'https://picsum.photos/id/1/400/300',
        description: 'Latest gadgets and tech accessories.',
    },
    {
        id: '2',
        name: 'Fashion',
        slug: 'fashion',
        image: 'https://picsum.photos/id/103/400/300',
        description: 'Trendy clothing for men and women.',
    },
    {
        id: '3',
        name: 'Home & Living',
        slug: 'home-living',
        image: 'https://picsum.photos/id/102/400/300',
        description: 'Decor and essentials for your home.',
    },
    {
        id: '4',
        name: 'Books',
        slug: 'books',
        image: 'https://picsum.photos/id/24/400/300',
        description: 'Bestsellers, fiction, and non-fiction.',
    },
];

export const products = [
    {
        id: '1',
        name: 'Wireless Noise Cancelling Headphones',
        slug: 'wireless-headphones',
        price: 299.99,
        category: 'electronics',
        rating: 4.8,
        reviews: 128,
        image: 'https://picsum.photos/id/14/600/600',
        images: [
            'https://picsum.photos/id/14/600/600',
            'https://picsum.photos/id/15/600/600',
            'https://picsum.photos/id/16/600/600',
        ],
        description: 'Experience premium sound quality with our latest noise-cancelling headphones. Featuring 30-hour battery life and ultra-comfortable ear cushions.',
        features: ['Active Noise Cancellation', '30hr Battery', 'Bluetooth 5.0'],
        isNew: true,
    },
    {
        id: '2',
        name: 'Minimalist Wrist Watch',
        slug: 'minimalist-watch',
        price: 149.00,
        category: 'fashion',
        rating: 4.6,
        reviews: 85,
        image: 'https://picsum.photos/id/17/600/600',
        images: [
            'https://picsum.photos/id/17/600/600',
            'https://picsum.photos/id/18/600/600',
        ],
        description: 'A sleek and modern timepiece for the everyday professional. Water-resistant and durable stainless steel build.',
        features: ['Water Resistant', 'Stainless Steel', 'Sapphire Glass'],
        isNew: false,
    },
    {
        id: '3',
        name: 'Geometric table lamp',
        slug: 'geometric-lamp',
        price: 79.50,
        category: 'home-living',
        rating: 4.9,
        reviews: 42,
        image: 'https://picsum.photos/id/20/600/600',
        images: ['https://picsum.photos/id/20/600/600'],
        description: 'Add a touch of modern art to your living room with this geometric table lamp. Soft ambient lighting.',
        features: ['LED Bulb Included', 'Ceramic Base', 'Dimmable'],
        isNew: true,
    },
    {
        id: '4',
        name: 'Professional DSLR Camera',
        slug: 'dslr-camera',
        price: 1299.00,
        category: 'electronics',
        rating: 4.9,
        reviews: 210,
        image: 'https://picsum.photos/id/250/600/600',
        images: ['https://picsum.photos/id/250/600/600'],
        description: 'Capture life in stunning detail. 24MP sensor, 4K video recording, and weather-sealed body.',
        features: ['24MP Sensor', '4K Video', 'Wifi Enabled'],
        isNew: false,
    },
    {
        id: '5',
        name: 'Leather Messenger Bag',
        slug: 'leather-bag',
        price: 195.00,
        category: 'fashion',
        rating: 4.7,
        reviews: 56,
        image: 'https://picsum.photos/id/30/600/600',
        images: ['https://picsum.photos/id/30/600/600'],
        description: 'Handcrafted genuine leather bag. Spacious compartments for laptop and documents.',
        features: ['Genuine Leather', 'Fits 15" Laptop', 'Adjustable Strap'],
        isNew: false,
    },
    {
        id: '6',
        name: 'Smart Home Hub',
        slug: 'smart-hub',
        price: 129.99,
        category: 'electronics',
        rating: 4.5,
        reviews: 30,
        image: 'https://picsum.photos/id/3/600/600',
        images: ['https://picsum.photos/id/3/600/600'],
        description: 'Control your entire home with voice commands. Compatible with thousands of smart devices.',
        features: ['Voice Control', 'Touch Screen', 'Easy Setup'],
        isNew: true,
    },
];

export const cartItems = [
    {
        productId: '1',
        quantity: 1,
        product: products[0],
    },
    {
        productId: '3',
        quantity: 2,
        product: products[2],
    },
];
